apiVersion: v1
kind: Service
metadata:
  name: mlflask-service
spec:
  selector:
    app: mlflask
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflask
spec:
  selector:
    matchLabels:
      app: mlflask
  replicas: 4
  template:
    metadata:
      labels:
        app: mlflask
    spec:
      containers:
      - name: mlflask
        image: neeraj2mail/ml-flask:v0.0.1
        #imagePullPolicy: Never
        ports:
        - containerPort: 8080